# ASR Fine-tuning Hyperparameters

# Data paths
train_csv: "/home/bchristensen/random_split/train.csv"
valid_csv: "/home/bchristensen/random_split/val.csv"
test_csv: "/home/bchristensen/random_split/test.csv"

# Model selection
model_name: "openai/whisper-medium"  # or "openai/whisper-small"

# Training hyperparameters
batch_size: 8
learning_rate: 1e-4
num_epochs: 10

# Optimizer
optimizer: !name:torch.optim.AdamW
  lr: !ref <learning_rate>

# Loss and metrics
ce_loss: !name:speechbrain.nnet.losses.nll_loss
error_rate: !name:speechbrain.utils.metric_stats.ErrorRateStats

# Checkpointing
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: "./fine-tuning/checkpoints"

# Epoch counter for training
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
  limit: !ref <num_epochs>